### PR TITLE
Fix epex spot web scraper url

### PR DESCRIPTION
**Pull request by suaveolent**
The EPEX Spot data url seems to have been changed. This PR solves the issue.

### CODE REVIEW

**Comment by suaveolent** [comment]
> Update 3.0.0-dev4 fixed the problem, scraper is working again. many thanks for the ongoing support!!!

Great. Thanks for confirming 🚀

**Comment by lieven121** [comment]
Will this fix come to v2 or should I already switch to 3v dev?

**Comment by lieven121** [comment]
@suaveolent thx for the reply and info

If i have time this weekend i will make a backup and move my automations to v3 (probably i will do divide by 100 for now)

**Comment by suaveolent** [comment]
I also just released version `2.3.9` with the cherry-picked fix in case you want to have a fix now.

**Pull request merged**
