### PR TITLE
Add Tibber energy price source

### PR DESCRIPTION
**Pull request by RustyDust**
This PR adds support for Tibber as the source of electricity prices. You need to have an account with Tibber and you also need to get an access token for their API from https://developer.tibber.com

### Motivation:
I thought it'd be nice to be able to
- see the future prices for Tibber (their HA integration only provides the current hour)
- be able to compare Tibber to EPEX spot prices and maybe competitors too

### Minor issue
I found no easy way to disable the configuration of `tax`, `percentage surcharge` and `absolute surcharge`. Those aren't needed for Tibber since they already provide net prices for the current customer as identified through the API token. If given, those values are silently ignored for Tibber.

### CODE REVIEW

**Comment by mampfes** [comment]
Hi, thanks for your contribution. I'm still think whether it is a good idea to merge this PR. The reason is that I can't maintain the code as I don't have a Tibber account.

**Comment by RustyDust** [comment]
You don't need an account. You can find the official demo token in line 63 of the `__init__.py`.

**Comment by RustyDust** [comment]
Oh, and of course if need be, I'd do the maintenance.

**Comment by mampfes** [comment]
Ok, then I will merge it (into development branch first). I want to add some breaking changes before I will release a new version=.

**Pull request merged**
