### PR TITLE
Adding Energyforecast.de as a data source

### PR DESCRIPTION
**Pull request by moritzmair**
As discussed in [This issue](https://github.com/mampfes/ha_epex_spot/issues/146) I added a Integration for my energy price forecast site. Hope this helps to bring energy price forecasts to many users and in their smart home. For now only DE prices are supported.

This is how it looks like with Apex Charts:
image

### CODE REVIEW

**Comment by suaveolent** [comment]
Thanks, I will review it as soon as possible 👍

**Comment by suaveolent** [comment]
@moritzmair Unfortuntately the test does not work for me.

```
ha_epex_spot/custom_components/epex_spot/test_energyforecast.py", line 14, in main
    service = Energyforecast.Energyforecast(token=DEMO_TOKEN, session=session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Energyforecast.__init__() missing 1 required positional argument: 'market_area'
```

**Comment by moritzmair** [comment]
@suaveolent I will fix it asap

**Comment by moritzmair** [comment]
okay just fixed the test, also made the "demo_token" a working token on my side. Also added the new data source to the readme.

**Review by suaveolent — CHANGES_REQUESTED** [review]

**Review by suaveolent — APPROVED** [review]

**Pull request merged**
