### PR TITLE
Fix tax calculation

### PR DESCRIPTION
**Pull request by Isopres**
The tax must be calculated before the surcharges

### CODE REVIEW

**Comment by mampfes** [comment]
Please explain the reasoning for this change.

The current implementation matches the documentation in README.md. What is wrong with that?

**Comment by mr-p666** [comment]
In most cases it is sufficient to simply deduct the tax from your surcharges and enter it. 😉
In all other cases (e.g. different tax rate for energy prices than surcharges) it becomes quite complicated.
But maybe you can give us an example to understand your requirement.

**Comment by Isopres** [comment]
Sorry, my English is not the best.

Example Tibber in Germany:
Percentage Surcharge (%) = 0
Absolute Surcharge (ct/kWh) = 18.39
Tax (%) = 19

EPEX Spot Data Price = 0,61 EUR/MWh

old calculation: 21.96 (ct/kWh)

new calculation: 18,46 (ct/kWh)

Price Tibber App: 18 (ct/kWh)


Unfortunately I can't test the percentage surcharge, but the tax should be calculated before the absolute surcharge.
According to Tibber, taxes are already included in the Absolute Surcharge.

**Comment by mampfes** [comment]
Ok, in this case you can just do the following:
Set Percentage surcharge to 19.
Set Absolute surcharge to 18.39.
Set Tax to 0.

This gives you exactly want you want, because "Percentage Surcharge" is added before "Absolute Surcharge".
"Percentage Surcharge", "Absolute Surcharge" and "Tax" are just names for parts of a formula, you can use arbitrary values for them.

**Comment by Isopres** [comment]
Ok then sorry

**Pull request closed without merging**
