### PR TITLE
Fix price calculation for Smart Energy

### PR DESCRIPTION
**Pull request by suaveolent**
See: https://github.com/mampfes/ha_epex_spot/issues/108#issuecomment-2466891863

Price needs to be calculated: spot price *1,2 + 1.44.

### CODE REVIEW

**Comment by clutwo** [comment]
Hi, just installed version 3.0.0-dev2. Net Price for SmartEnergy now seems to be faulty.

image

As you can see, Net Price is now just Price x 10 rounded to 2 decimals for some reason.

**Comment by suaveolent** [comment]
Unfortunately there seems to be an issue with migration of the user options. You need to change the surcharge.

**Comment by clutwo** [comment]
image

Hmm thanks, tried changing all the settings, it still shows over 1.32 €/kwh which is of course way off.

**Comment by suaveolent** [comment]
The price surcharge is now also in €/kWh and not ct. So you need to change it from e.g. 1.2 to 0.012

**Comment by clutwo** [comment]
Ah right, could have thought of that myself. Thanks and sorry for the bother!

**Comment by halms** [comment]
I think Smartenergy should not be treated differently than others here. `net_p` should always be the spot price and then everyone can configure what they want for surcharges.
The existing calculation was sufficient. It was just a matter of setting `0.12` or `0.144` as the absolute surcharge.

Now smartenergy first adds the tax and all others first add the surcharge and then the tax, leading to different values depending on which source one uses for the same configuration.

I actually want my gross price to include all grid fees and taxes so that I can see the actual cost – this change broke this behavior.

**Comment by suaveolent** [comment]
> I think Smartenergy should not be treated differently than others here. `net_p` should always be the spot price and then everyone can configure what they want for surcharges. The existing calculation was sufficient. It was just a matter of setting `0.12` or `0.144` as the absolute surcharge.
> 
> Now smartenergy first adds the tax and all others first add the surcharge and then the tax, leading to different values depending on which source one uses for the same configuration.
> 
> I actually want my gross price to include all grid fees and taxes so that I can see the actual cost – this change broke this behavior.

You are right. It’s true that having different methods of calculating surcharges can lead to confusion.

In the end, however, there will always be confusion as to why the 0.0144€ charged by smartenergy should not be used. (Which this was changed in the first place).

What do other users think about that?

**Comment by mr-p666** [comment]
I also have SmartEnergy as my energy delivery service but I'm with @halms. It should always be the same way to calculate it and as you say @suaveolent, there will always be a confusion and we don't need to push it with unnessecary additional sensors or input parameter.

**Pull request merged**
