### PR TITLE
Change from ct/kWh to currency/kWh

### PR DESCRIPTION
**Pull request by suaveolent**
This PR changes the unit from ct/kWh to €/£/mWh/kWh as preferred by Home Assistant (see https://github.com/mampfes/ha_epex_spot/discussions/122).

### Changes as requested in https://github.com/mampfes/ha_epex_spot/pull/128
 - Rename to `price_per_kwh`
 -  only return price_per_kwh -> removed price_eur_per_mwh and price_ct_per_kwh
 - Change default surcharge unit

### CODE REVIEW

**Comment by ericdevos** [comment]
I would really like this!

**Comment by suaveolent** [comment]
@mampfes is there anything you need from my side to merge this ?

**Comment by mampfes** [comment]
@suaveolent Sorry for the delay - I'm too busy with other projects and don't have the time maintain this integration at the moment. Do you want to help me and become a maintainer?

**Comment by suaveolent** [comment]
Sure thing 👍

**Pull request merged**
